### ISSUE TITLE
systemctl enable can't find Overwatch.service

### ISSUE THREAD

**Issue by dlarue** [easytarget/pi-overwatch#37]
Running Rasbian Buster 10 and installed as the docs described, linked Overwatch.service to /etc/systemd/system as described(full paths) and verified it's there.  I try to enable and it states system unit Overwatch.service doesn't exist but what's really weird is that I can start and restart the service( sudo systemctl start Overwatch.service ) just fine.  Although, systemctl status does show that it is running  /home/pi/HAT/pi-overwatch/Overwatch.service and not /etc/systemd/Overwatch.service. 

Any ideas on why?

**Comment by dlarue** [comment]
Never mind... Overwatch.service should be OverWatch.service.

**Comment by easytarget** [comment]
Sorry you got caught by that, I am following the 'convention' of using CamelCase for user installed services.

**Comment by dlarue** [comment]
it was a forehead slapper... and I use camelCase all the time, just didn't notice wW and should have when the auto-complete was working for systemctl start but not enable. All good, just need to get my eyes checked. LOL
